### ISSUE TITLE
issue-5-search-through-entries

### ISSUE THREAD

**Issue by c-alvin** [c-alvin/code-journal#9]
## 📐 Plan

User can search their entries. Provide a search box that causes the entries list to only show matches.

## ✅ Task List

- [x] add a search input bar to the header.
- [x] set a criteria to search for, such as matching titles.
- [ ] once a criteria to search for has been submitted create an event listener for the input
- [ ] make a function that swaps view to an entries list that matches the search. Dom trees will have to be added based on matching criteria.
- [ ] Clean up all unnecessary styling.
- [ ] Test the app some more in a private browsing tab.
- [ ] Fix all errors.
